### ISSUE TITLE
Travis no longer sending emails to a mailing list

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3031]
Ever since we first set it up, Travis has been configured to send email to the dynamorio-devs list.  But it is no longer sending emails: the last one was March 20.

Xref the docs https://docs.travis-ci.com/user/notifications/

I did check the list's pending message and there's nothing there.  It is set up to allow anyone to post.

I tried the following code in .travis.yml:

I did get email with the default target:
```
notifications:
  email:
    on_success: always
    on_failure: always
```

Neither I nor the list got email with any of these:
```
notifications:
  email:
    # This overrides the default of sending to the committer and author.
    recipients:
      - dynamorio-devs@googlegroups.com
    on_success: change
    on_failure: always
```
```
notifications:
  email:
    # This overrides the default of sending to the committer and author.
    # Temporarily sending to bruening too to help diagnose email problems.
    recipients:
      - dynamorio-devs@googlegroups.com
      - bruening@google.com
    on_success: always
    on_failure: always
```
```
notifications:
  email:
    # This overrides the default of sending to the committer and author.
    # Temporarily sending to bruening too to help diagnose email problems.
    recipients:
      - bruening@google.com
    on_success: always
    on_failure: always
```
