### ISSUE TITLE
package building is failing with "Error: Unable to download artifact(s): Artifact not found for name: linux-tarball"

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#6981]
The last weekly cronbuild and the manual retry I kicked off both failed with "Error: Unable to download artifact(s): Artifact not found for name: linux-tarball".  Needs investigation as the Linux build is marked green.

https://github.com/DynamoRIO/dynamorio/actions/workflows/ci-package.yml

**Comment by abhinav92003** [comment]
Is the issue that we're not using the same version for the upload and download actions?

```
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-tarball
```

and

```
    - name: Download Linux
      uses: actions/download-artifact@v4.1.7
      with:
        name: linux-tarball
```
